name: core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @rumble/core run build
      - run: yarn workspace @rumble/core run lint:check
      - run: yarn workspace @rumble/core run format:check
